### ISSUE TITLE
[Bug]: If I don't specify max_ratio it gets added as -1 after the next run.

### ISSUE THREAD

**Issue by bobokun** [StuffAnThings/qbit_manage#196]
If I don't specify max_ratio it gets added as -1 after the next run.
Is there a reason for that? In cample configuration, it says it's optional, this makes it looks as if it's mandatory. 

I would just want to know what files aren't hard-linked and not mess with the ratio, that I have set in with tags.

_Originally posted by @pax0707 in https://github.com/StuffAnThings/qbit_manage/discussions/195_

**Comment by bobokun** [comment]
@pax0707 can you try the develop branch? This should be fixed

**Comment by pax0707** [comment]
@bobokun Fixed.

Removed all the tags, and run it again - ratios are as they should be by tags.

**Comment by Quafley** [comment]
Since my post has been mentioned in this one and is a duplicate, I'll react here. The problem still seems to exist. I have removed the max_ratio from my NoHL category, which should result in it following the ratio set up by the tracker (just like upload), yet it does not, and this results in torrents seeding way more than they should. This has both been tested on the main and dev build.
